# Generated by Django 6.0 on 2025-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_Category',
            field=models.IntegerField(),
        ),
    ]
