# Generated by Django 6.0 on 2025-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_room_rent_per_day_in_nepali_rupees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_Category_In_Stars',
            field=models.TextField(default=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Room_Rent_Per_Day_In_Nepali_Rupees',
            field=models.TextField(default=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Total_Rooms_Available',
            field=models.TextField(default=10),
        ),
    ]
