# Generated by Django 6.0 on 2025-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_hotel_category_in_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_Category_In_Stars',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Room_Rent_Per_Day_In_Nepali_Rupees',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Total_Rooms_Available',
            field=models.IntegerField(default=10),
        ),
    ]
