# Generated by Django 6.0 on 2025-12-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Provider', models.CharField(max_length=30)),
                ('Dream_Continent', models.CharField(choices=[('Asia', 'ASIA'), ('Africa', 'AFRICA'), ('South America', 'SOUTH AMERICA'), ('North America', 'NORTH AMERICA'), ('Europe', 'EUROPE'), ('Australia', 'AUSTRALIA')], max_length=15)),
                ('Trip_Difficulty', models.CharField(choices=[('Easy', 'EASY'), ('Moderate', 'MODERATE'), ('Challenging', 'CHALLENGING')], max_length=15)),
                ('Interest', models.CharField(choices=[('Beach', 'BEACH'), ('Mountain', 'MOUNTAINS'), ('Adventure', 'ADVENTURE'), ('Religious', 'RELIGIOUS'), ('Treeking', 'TREEKING'), ('Camping', 'CAMPING'), ('City', 'CITY TOUR')], max_length=15)),
                ('Trip_Category', models.CharField(choices=[('Group Tour', 'GROUP TOUR'), ('Solo Trip', 'SOLO TRIP'), ('Family Package', 'FAMILY PACKAGE'), ('Couple Package', 'COUPLE PACKAGE'), ('Corporate Tour', 'CORPORATE TOUR')], max_length=15)),
                ('Accomodation', models.CharField(choices=[('Hotel', 'HOTEL'), ('Resort', 'RESORT'), ('Homestay', 'HOMESTAY'), ('Hostel', 'HOSTEL'), ('Luxury Stay', 'LUXURY STAY')], max_length=20)),
                ('Highlights', models.TextField()),
                ('Total_Estimated_Cost', models.IntegerField()),
                ('Total_Estimated_Duration', models.CharField()),
            ],
        ),
    ]
