# Generated by Django 6.0 on 2025-12-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='Dream_Continent',
            new_name='Continent',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='Interest',
            new_name='Type',
        ),
    ]
