# Generated by Django 6.0 on 2025-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=180)),
            ],
        ),
    ]
