# Generated by Django 6.0 on 2025-12-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desired_travel_destination',
            old_name='User',
            new_name='user',
        ),
    ]
