# Generated by Django 6.0 on 2025-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0002_rename_user_desired_travel_destination_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='desired_travel_destination',
            name='Description_Image_1',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='desired_travel_destination',
            name='Description_Image_2',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='desired_travel_destination',
            name='Description_Image_3',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='desired_travel_destination',
            name='Description_Image_4',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='desired_travel_destination',
            name='Thumbnail_Image',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='image'),
        ),
    ]
