# Generated by Django 6.0 on 2025-12-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0004_remove_desired_travel_destination_description_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='user',
        ),
    ]
