CAR_COLOR_CHOICE = (
    ('BLACK', 'Black'),
    ('WHITE', 'White'),
    ('SILVER', 'Silver'),
    ('GRAY', 'Gray'),
    ('RED', 'Red'),
    ('BLUE', 'Blue'),
    ('GREEN', 'Green'),
    ('YELLOW', 'Yellow'),
    ('ORANGE', 'Orange'),
    ('BROWN', 'Brown'),
    ('BEIGE', 'Beige'),
    ('GOLD', 'Gold'),
    ('PURPLE', 'Purple'),
    ('PINK', 'Pink'),
    ('MAROON', 'Maroon'),
    ('NAVY', 'Navy Blue'),
    ('TEAL', 'Teal'),
    ('TURQUOISE', 'Turquoise'),
    ('BRONZE', 'Bronze'),
    ('CHAMPAGNE', 'Champagne'),
)
