# Generated by Django 6.0 on 2025-12-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_destinations', '0003_desired_travel_destination_description_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='Description_Image_1',
        ),
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='Description_Image_2',
        ),
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='Description_Image_3',
        ),
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='Description_Image_4',
        ),
        migrations.RemoveField(
            model_name='desired_travel_destination',
            name='Thumbnail_Image',
        ),
    ]
