# Generated by Django 6.0 on 2025-12-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=100)),
                ('Hotel_Category', models.IntegerField(default=2)),
                ('Hotel_Location', models.CharField(max_length=100)),
                ('Total_Rooms_Available', models.IntegerField(default=10)),
                ('Room_Description', models.TextField()),
                ('Room_Rent_Per_Day_In_Nepali_Rupees', models.IntegerField(default=1000)),
                ('Hotel_Owner_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
