# Generated by Django 6.0 on 2025-12-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_hotel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Hotel_Category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='Hotel_Category_In_Stars',
            field=models.CharField(default='2 star'),
        ),
    ]
