# Generated by Django 6.0 on 2025-12-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_hotel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Room_Rent_Per_Day_In_Nepali_Rupees',
            field=models.CharField(default='Rs. 2000'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Total_Rooms_Available',
            field=models.CharField(default='50 rooms available'),
        ),
    ]
